FROM gemstone-base:latest

WORKDIR /root

RUN wget https://files.jlab.space/openbdk-nx/rootfs-stage1.tar.gz

RUN mkdir -p /root/rootfs

RUN tar -xf ./rootfs-stage1.tar.gz -C /root/rootfs

RUN curl https://raw.githubusercontent.com/junland/generic-toolbox/master/scripts/rootfs-test.sh > /usr/local/bin/rootfs-test.sh && chmod +x /usr/local/bin/rootfs-test.sh

RUN curl https://raw.githubusercontent.com/junland/generic-toolbox/master/files/test.c > /root/rootfs/test.c

ENTRYPOINT ["/bin/bash", "-c"]
