FROM gemstone-base:latest

ARG BARCH=x86_64

ARG BBRANCH=master

ENV BUILD_ARCH=$BARCH

ENV GIT_BRANCH=$BBRANCH

ENV PACKAGE_ALL=yes

WORKDIR /root

RUN git clone --branch $GIT_BRANCH https://github.com/junland/openbdk-nx.git

WORKDIR /root/openbdk-nx

RUN make prep

RUN cp utils/bootstrap /usr/local/bin

ENTRYPOINT ["/bin/bash", "-c"]
